# Generated by Django 3.2.6 on 2022-11-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20221125_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='1.jpg', upload_to='static/product'),
        ),
    ]
