version: '3.9'

services:
  django:
    image: django-stripe-docker:0.0.1
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "cd tutorial &&
             python manage.py makemigrations && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"


